# Generated by Django 4.2.5 on 2023-12-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(default='Thu Dec 21 11:51:50 2023', max_length=20)),
                ('category', models.CharField(default='category', max_length=20)),
                ('amount', models.FloatField()),
                ('age', models.FloatField()),
                ('name', models.CharField(default='Thu Dec 21 11:51:50 2023', max_length=20)),
                ('gender', models.CharField(default='alien', max_length=20)),
            ],
        ),
    ]
