# Generated by Django 4.2.5 on 2023-12-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Date',
            field=models.CharField(default='Thu Dec 21 16:19:24 2023', max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(default='Thu Dec 21 16:19:24 2023', max_length=20),
        ),
    ]
