# Generated by Django 4.2.5 on 2023-12-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rome', '0002_alter_register_date_alter_register_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Date',
            field=models.CharField(default='Thu Dec 21 17:04:44 2023', max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(default='Thu Dec 21 17:04:44 2023', max_length=20),
        ),
    ]
