# Generated by Django 4.2.5 on 2023-12-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rome', '0003_alter_register_date_alter_register_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Date',
            field=models.CharField(default='Fri Dec 22 12:31:59 2023', max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(default='Fri Dec 22 12:31:59 2023', max_length=20),
        ),
    ]
