# Generated by Django 4.2.5 on 2023-12-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rome', '0007_alter_register_date_alter_register_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Date',
            field=models.CharField(default='Fri Dec 22 13:39:56 2023', max_length=40),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(default='Fri Dec 22 13:39:56 2023', max_length=255),
        ),
    ]
